#!/usr/bin/env sh

./gradlew :library:clean :library:build :library:publish --no-daemon --no-parallel && \
./gradlew :ui-rx:clean :ui-rx:build :ui-rx:publish --no-daemon --no-parallel

if ! grep -q -- "VERSION_NAME=.*-SNAPSHOT" gradle.properties;
then
./gradlew closeAndReleaseRepository
else
echo "Nothing else to do for a snapshot"
fi
